import { Container, Flex } from '@radix-ui/themes';
import { Metadata } from 'next';
import { PropsWithChildren } from 'react';

import { Header } from '@/components';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

function Template({ children }: PropsWithChildren) {
  return (
    <Container style={{ padding: '1rem' }}>
      <Flex direction="column" gap="6">
        <Header />
        {children}
      </Flex>
    </Container>
  );
}

export default Template;
